// <auto-generated />
using System;
using DeviceManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeviceManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210526001513_202105260815")]
    partial class _202105260815
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DeviceManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DeviceManagement.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassName")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceDetailId")
                        .HasColumnType("int");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<string>("LogPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceDetailId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceManagement.Models.DeviceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("AirPress")
                        .HasColumnType("float");

                    b.Property<double>("AirPressMax")
                        .HasColumnType("float");

                    b.Property<double>("AirPressMin")
                        .HasColumnType("float");

                    b.Property<bool>("AutoValve")
                        .HasColumnType("bit");

                    b.Property<double>("ChangOilTime")
                        .HasColumnType("float");

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CloseValve")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DownDuring")
                        .HasColumnType("float");

                    b.Property<bool>("DownMotor")
                        .HasColumnType("bit");

                    b.Property<int>("ErrorNum")
                        .HasColumnType("int");

                    b.Property<int>("ErrorNum1")
                        .HasColumnType("int");

                    b.Property<int>("ErrorNum2")
                        .HasColumnType("int");

                    b.Property<int>("ErrorNum3")
                        .HasColumnType("int");

                    b.Property<int>("ErrorNum4")
                        .HasColumnType("int");

                    b.Property<int>("ErrorNum5")
                        .HasColumnType("int");

                    b.Property<int>("ErrorNum6")
                        .HasColumnType("int");

                    b.Property<string>("GasAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HighPressDuring")
                        .HasColumnType("float");

                    b.Property<double>("HighPressEndP")
                        .HasColumnType("float");

                    b.Property<double>("HighPressStartP")
                        .HasColumnType("float");

                    b.Property<bool>("HoldStove")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChangeOilTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("LowPressDuring")
                        .HasColumnType("float");

                    b.Property<double>("LowPressEndP")
                        .HasColumnType("float");

                    b.Property<double>("LowPressStartP")
                        .HasColumnType("float");

                    b.Property<string>("MotorAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpenValve")
                        .HasColumnType("bit");

                    b.Property<string>("PumpAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenorAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StandardAirPress")
                        .HasColumnType("float");

                    b.Property<double>("StandardAirTemp")
                        .HasColumnType("float");

                    b.Property<bool>("StartStove")
                        .HasColumnType("bit");

                    b.Property<bool>("StopMotor")
                        .HasColumnType("bit");

                    b.Property<bool>("StopStove")
                        .HasColumnType("bit");

                    b.Property<string>("StoveAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StoveAirTemp")
                        .HasColumnType("float");

                    b.Property<double>("StoveTempMax")
                        .HasColumnType("float");

                    b.Property<double>("StoveTempMin")
                        .HasColumnType("float");

                    b.Property<double>("UpDuring")
                        .HasColumnType("float");

                    b.Property<bool>("UpMotor")
                        .HasColumnType("bit");

                    b.Property<double>("UseDuring")
                        .HasColumnType("float");

                    b.Property<double>("VacuumPress")
                        .HasColumnType("float");

                    b.Property<string>("ValveAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningNum")
                        .HasColumnType("int");

                    b.Property<int>("WarningNum1")
                        .HasColumnType("int");

                    b.Property<int>("WarningNum2")
                        .HasColumnType("int");

                    b.Property<int>("WarningNum3")
                        .HasColumnType("int");

                    b.Property<int>("WarningNum4")
                        .HasColumnType("int");

                    b.Property<int>("WarningNum5")
                        .HasColumnType("int");

                    b.Property<int>("WarningNum6")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeviceDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DeviceManagement.Models.Device", b =>
                {
                    b.HasOne("DeviceManagement.Models.DeviceDetail", "DeviceDetail")
                        .WithMany()
                        .HasForeignKey("DeviceDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeviceDetail");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DeviceManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DeviceManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeviceManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DeviceManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
